version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - "postgres:postgres"
    env_file: .env
    command: bash -c "
      python manage.py migrate &&
      python manage.py loaddata categories.yaml &&
      gunicorn -b :8000 thehare.wsgi"

  postgres:
    image: postgres:latest
    expose:
      - 5432
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust