# Generated by Django 3.1.5 on 2021-01-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='contents_file',
            field=models.FileField(default='dummy.md', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.ImageField(default='dummy.png', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
