# Generated by Django 3.1.5 on 2021-01-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
