# Generated by Django 3.1.5 on 2021-01-07 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210107_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_profiles', to='auth.user'),
            preserve_default=False,
        ),
    ]
