# Generated by Django 3.1.5 on 2021-01-09 15:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210107_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents_file',
            field=models.FileField(upload_to=core.models.RenameFile('res/articles/'), validators=[core.models.FileValidator(['text/markdown', 'text/plain'], ['.md'])]),
        ),
    ]
