# Generated by Django 3.1.5 on 2021-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210109_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
